<a href="https://colab.research.google.com/github/ewotawa/secure_private_ai/blob/master/Section_2_Federated_Learning_Work_Copy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Section: Federated Learning

# Lesson: Introducing Federated Learning

Federated Learning is a technique for training Deep Learning models on data to which you do not have access. Basically:

Federated Learning: Instead of bringing all the data to one machine and training a model, we bring the model to the data, train it locally, and merely upload "model updates" to a central server.

Use Cases:

    - app company (Texting prediction app)
    - predictive maintenance (automobiles / industrial engines)
    - wearable medical devices
    - ad blockers / autotomplete in browsers (Firefox/Brave)
    
Challenge Description: data is distributed amongst sources but we cannot aggregated it because of:

    - privacy concerns: legal, user discomfort, competitive dynamics
    - engineering: the bandwidth/storage requirements of aggregating the larger dataset

# Lesson: Introducing / Installing PySyft

In order to perform Federated Learning, we need to be able to use Deep Learning techniques on remote machines. This will require a new set of tools. Specifically, we will use an extensin of PyTorch called PySyft.

### Install PySyft

The easiest way to install the required libraries is with [Conda](https://docs.conda.io/projects/conda/en/latest/user-guide/overview.html). Create a new environment, then install the dependencies in that environment. In your terminal:

```bash
conda create -n pysyft python=3
conda activate pysyft # some older version of conda require "source activate pysyft" instead.
conda install jupyter notebook
pip install syft
pip install numpy
```

If you have any errors relating to zstd - run the following (if everything above installed fine then skip this step):

```
pip install --upgrade --force-reinstall zstd
```

and then retry installing syft (pip install syft).

If you are using Windows, I suggest installing [Anaconda and using the Anaconda Prompt](https://docs.anaconda.com/anaconda/user-guide/getting-started/) to work from the command line. 

With this environment activated and in the repo directory, launch Jupyter Notebook:

```bash
jupyter notebook
```

and re-open this notebook on the new Jupyter server.

If any part of this doesn't work for you (or any of the tests fail) - first check the [README](https://github.com/OpenMined/PySyft.git) for installation help and then open a Github Issue or ping the #beginner channel in our slack! [slack.openmined.org](http://slack.openmined.org/)

Colab install PySyft, PyTorch, dependencies, libraries

In [178]:
# PySyft
# Install prerequisite for install

# ERROR: syft 0.1.19a1 has requirement msgpack>=0.6.1, but you'll have msgpack 0.5.6 which is incompatible.

!pip install --upgrade --force-reinstall msgpack

  Using cached https://files.pythonhosted.org/packages/92/7e/ae9e91c1bb8d846efafd1f353476e3fd7309778b582d2fb4cea4cc15b9a2/msgpack-0.6.1-cp36-cp36m-manylinux1_x86_64.whl
  Found existing installation: msgpack 0.6.1
    Uninstalling msgpack-0.6.1:
      Successfully uninstalled msgpack-0.6.1


In [179]:
# PySyft
# Install dependencies

# https://github.com/OpenMined/PySyft
# https://colab.research.google.com/drive/14tNU98OKPsP55Y3IgFtXPfd4frqbkrxK#scrollTo=qpX6fqECKGyk

!pip install tf-encrypted

! URL="https://github.com/openmined/PySyft.git" && FOLDER="PySyft" && if [ ! -d $FOLDER ]; then git clone -b dev --single-branch $URL; else (cd $FOLDER && git pull $URL && cd ..); fi;

!cd PySyft; python setup.py install  > /dev/null

import os
import sys
module_path = os.path.abspath(os.path.join('./PySyft'))
if module_path not in sys.path:
    sys.path.append(module_path)
    
!pip install --upgrade --force-reinstall lz4
!pip install --upgrade --force-reinstall websocket
!pip install --upgrade --force-reinstall websockets
!pip install --upgrade --force-reinstall zstd

From https://github.com/openmined/PySyft
 * branch              HEAD       -> FETCH_HEAD
Already up to date.
zip_safe flag not set; analyzing archive contents...
  Using cached https://files.pythonhosted.org/packages/0a/c6/96bbb3525a63ebc53ea700cc7d37ab9045542d33b4d262d0f0408ad9bbf2/lz4-2.1.10-cp36-cp36m-manylinux1_x86_64.whl
  Found existing installation: lz4 2.1.10
    Uninstalling lz4-2.1.10:
      Successfully uninstalled lz4-2.1.10


  Using cached https://files.pythonhosted.org/packages/f2/ca/5b5962361ed832847b6b2f9a2d0452c8c2f29a93baef850bb8ad067c7bf9/gevent-1.4.0-cp36-cp36m-manylinux1_x86_64.whl
  Using cached https://files.pythonhosted.org/packages/bf/45/142141aa47e01a5779f0fa5a53b81f8379ce8f2b1cd13df7d2f1d751ae42/greenlet-0.4.15-cp36-cp36m-manylinux1_x86_64.whl
  Found existing installation: greenlet 0.4.15
    Uninstalling greenlet-0.4.15:
      Successfully uninstalled greenlet-0.4.15
  Found existing installation: gevent 1.4.0
    Uninstalling gevent-1.4.0:
      Successfully uninstalled gevent-1.4.0
  Found existing installation: websocket 0.2.1
    Uninstalling websocket-0.2.1:
      Successfully uninstalled websocket-0.2.1


  Using cached https://files.pythonhosted.org/packages/61/5e/2fe6afbb796c6ac5c006460b5503cd674d33706660337f2dbff10d4aa12d/websockets-8.0-cp36-cp36m-manylinux1_x86_64.whl
  Found existing installation: websockets 8.0
    Uninstalling websockets-8.0:
      Successfully uninstalled websockets-8.0


  Found existing installation: zstd 1.4.0.0
    Uninstalling zstd-1.4.0.0:
      Successfully uninstalled zstd-1.4.0.0


In [180]:
# PySyft
# make sure nothing's missing.

!pip install syft
!pip install numpy

In [181]:
# PyTorch
# Install Dependencies
# https://colab.research.google.com/drive/1gJAAN3UI9005ecVmxPun5ZLCGu4YBtLo#scrollTo=XiHYo3hEhwdk

!pip3 install torch torchvision

In [182]:
# Import libraries
# https://colab.research.google.com/drive/14tNU98OKPsP55Y3IgFtXPfd4frqbkrxK#scrollTo=ZgomH7s4R5cT

from __future__ import print_function
import argparse
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.utils
import torch.utils.data

torch.__version__

'1.1.0'

Coursework

In [0]:
# import torch as th

In [184]:
x = torch.tensor([1,2,3,4,5])
x

tensor([1, 2, 3, 4, 5])

In [0]:
y = x + x

In [186]:
print(y)

tensor([ 2,  4,  6,  8, 10])


In [0]:
import syft as sy

In [188]:
hook = sy.TorchHook(torch)

W0716 06:03:46.788506 140222424659840 hook.py:98] Torch was already hooked... skipping hooking process


In [189]:
torch.tensor([1,2,3,4,5])

tensor([1, 2, 3, 4, 5])

# Lesson: Basic Remote Execution in PySyft

## PySyft => Remote PyTorch

The essence of Federated Learning is the ability to train models in parallel on a wide number of machines. Thus, we need the ability to tell remote machines to execute the operations required for Deep Learning.

Thus, instead of using Torch tensors - we're now going to work with **pointers** to tensors. Let me show you what I mean. First, let's create a "pretend" machine owned by a "pretend" person - we'll call him Bob.

In [0]:
bob = sy.VirtualWorker(hook, id="bob")

In [191]:
bob._objects

{99952531149: tensor([1, 2, 3, 4, 5])}

In [0]:
x = torch.tensor([1,2,3,4,5])

In [0]:
x = x.send(bob)

In [194]:
bob._objects

{14853967438: tensor([1, 2, 3, 4, 5]), 99952531149: tensor([1, 2, 3, 4, 5])}

In [195]:
x.location

<VirtualWorker id:bob #objects:2>

In [196]:
x.id_at_location

14853967438

In [197]:
x.id

76119954016

In [198]:
x.owner

<VirtualWorker id:me #objects:0>

In [199]:
hook.local_worker

<VirtualWorker id:me #objects:0>

In [200]:
x

(Wrapper)>[PointerTensor | me:76119954016 -> bob:14853967438]

In [201]:
x = x.get()
x

tensor([1, 2, 3, 4, 5])

In [202]:
bob._objects

{99952531149: tensor([1, 2, 3, 4, 5])}

# Project: Playing with Remote Tensors

In this project, I want you to .send() and .get() a tensor to TWO workers by calling .send(bob,alice). This will first require the creation of another VirtualWorker called alice.

In [0]:
# try this project here!

My work

In [204]:
# Create a bob worker and an alice worker.
bob = sy.VirtualWorker(hook, id="bob")
alice = sy.VirtualWorker(hook, id="alice")

print("bob worker: ", bob._objects)
print("alice worker: ", alice._objects)

bob worker:  {99952531149: tensor([1, 2, 3, 4, 5])}
alice worker:  {49561515848: tensor([1, 1, 1, 1, 1])}


In [205]:
# Create a tensor to send to bob and alice
t = torch.rand(10)
print("tensor t: ", t)

tensor t:  tensor([0.0021, 0.2957, 0.2765, 0.3206, 0.1821, 0.0391, 0.7530, 0.0450, 0.6310,
        0.6267])


In [206]:
# Send tensor to the two workers.
t = t.send(bob, alice)

print("bob worker: ", bob._objects)
print("alice worker: ", alice._objects)
print("tensor t: ", t)

bob worker:  {99952531149: tensor([1, 2, 3, 4, 5]), 30020750238: tensor([0.0021, 0.2957, 0.2765, 0.3206, 0.1821, 0.0391, 0.7530, 0.0450, 0.6310,
        0.6267])}
alice worker:  {49561515848: tensor([1, 1, 1, 1, 1]), 26645586183: tensor([0.0021, 0.2957, 0.2765, 0.3206, 0.1821, 0.0391, 0.7530, 0.0450, 0.6310,
        0.6267])}
tensor t:  (Wrapper)>[MultiPointerTensor]
	-> (Wrapper)>[PointerTensor | me:37520547498 -> bob:30020750238]
	-> (Wrapper)>[PointerTensor | me:36871345124 -> alice:26645586183]


In [207]:
# Get tensor from the two workers. 

t = t.get()

print("bob worker: ", bob._objects)
print("alice worker: ", alice._objects)
print("tensor t: ", t)

bob worker:  {99952531149: tensor([1, 2, 3, 4, 5])}
alice worker:  {49561515848: tensor([1, 1, 1, 1, 1])}
tensor t:  [tensor([0.0021, 0.2957, 0.2765, 0.3206, 0.1821, 0.0391, 0.7530, 0.0450, 0.6310,
        0.6267]), tensor([0.0021, 0.2957, 0.2765, 0.3206, 0.1821, 0.0391, 0.7530, 0.0450, 0.6310,
        0.6267])]


Instructor's code

In [0]:
alice2 = sy.VirtualWorker(hook, id="alice2")
bob2 = sy.VirtualWorker(hook, id="bob2")

In [209]:
# a worker is a collection of projects.
alice2._objects
bob2._objects

{}

In [0]:
# create some data
x = torch.tensor([1, 2, 3, 4, 5])

In [211]:
# create a multi-pointer: a pointer that references multiple machines.
x_ptr = x.send(bob2, alice2)
x_ptr

(Wrapper)>[MultiPointerTensor]
	-> (Wrapper)>[PointerTensor | me:34119507626 -> bob2:74025025264]
	-> (Wrapper)>[PointerTensor | me:48471241493 -> alice2:36819350349]

In [212]:
# multi-pointer object "child": dictionary of the workers
x_ptr.child

MultiPointerTensor>{'bob2': (Wrapper)>[PointerTensor | me:34119507626 -> bob2:74025025264], 'alice2': (Wrapper)>[PointerTensor | me:48471241493 -> alice2:36819350349]}

In [213]:
# note: x_ptr.get() returns two objects instead of one.
x_ptr.get()

[tensor([1, 2, 3, 4, 5]), tensor([1, 2, 3, 4, 5])]

In [214]:
x = torch.tensor([1, 2, 3, 4, 5]).send(bob2, alice2)

# alternativey, sum the tensors together.
x.get(sum_results=True)

tensor([ 2,  4,  6,  8, 10])

# Lesson: Introducing Remote Arithmetic

In [0]:
x = torch.tensor([1,2,3,4,5]).send(bob)
y = torch.tensor([1,1,1,1,1]).send(bob)

In [216]:
x

(Wrapper)>[PointerTensor | me:94183120196 -> bob:80481866286]

In [217]:
y

(Wrapper)>[PointerTensor | me:41569104453 -> bob:99891796453]

In [0]:
z = x + y

In [219]:
z

(Wrapper)>[PointerTensor | me:60605989501 -> bob:30249409296]

In [220]:
z = z.get()
z

tensor([2, 3, 4, 5, 6])

In [221]:
z = torch.add(x,y)
z

(Wrapper)>[PointerTensor | me:17725692382 -> bob:24522100447]

In [222]:
z = z.get()
z

tensor([2, 3, 4, 5, 6])

In [0]:
x = torch.tensor([1.,2,3,4,5], requires_grad=True).send(bob)
y = torch.tensor([1.,1,1,1,1], requires_grad=True).send(bob)

In [0]:
z = (x + y).sum()

In [225]:
z.backward()

(Wrapper)>[PointerTensor | me:33367543027 -> bob:73347286743]

In [0]:
x = x.get()

In [227]:
x

tensor([1., 2., 3., 4., 5.], requires_grad=True)

In [228]:
x.grad

tensor([1., 1., 1., 1., 1.])

# Project: Learn a Simple Linear Model

In this project, I'd like for you to create a simple linear model which will solve for the following dataset below. You should use only Variables and .backward() to do so (no optimizers or nn.Modules). Furthermore, you must do so with both the data and the model being located on Bob's machine.

In [0]:
# try this project here!

### My work
First: figure out the linear model syntax.
Reference: [kaggle](https://www.kaggle.com/aakashns/pytorch-basics-linear-regression-from-scratch)

In [0]:
# A Toy Dataset
data = torch.tensor([[1.,1],[0,1],[1,0],[0,0]], requires_grad=True)
target = torch.tensor([[1.],[1], [0], [0]], requires_grad=True)

In [231]:
print("Data: ", data)
print("Target: ", target)
print("Data shape: ", data.shape)
print("Target shape: ", target.shape)

Data:  tensor([[1., 1.],
        [0., 1.],
        [1., 0.],
        [0., 0.]], requires_grad=True)
Target:  tensor([[1.],
        [1.],
        [0.],
        [0.]], requires_grad=True)
Data shape:  torch.Size([4, 2])
Target shape:  torch.Size([4, 1])


In [232]:
# Generate weights and biases
w = torch.randn(1, 2, requires_grad=True)
b = torch.randn(1, requires_grad=True)
print("weights: ", w)
print("bias: ", b)

weights:  tensor([[0.3639, 1.7560]], requires_grad=True)
bias:  tensor([-1.2370], requires_grad=True)


In [0]:
# Define the model
def model(x):
  return x @ w.t() + b

In [234]:
# Generate predictions
preds = model(data)
print(preds)

tensor([[ 0.8829],
        [ 0.5189],
        [-0.8731],
        [-1.2370]], grad_fn=<AddBackward0>)


In [0]:
# Define loss (Mean Squared Error)
def mse(t1, t2):
  diff = t1 - t2
  return torch.sum(diff * diff) / diff.numel()

In [236]:
# Compute loss
loss = mse(preds, target)
print(loss)

tensor(0.6344, grad_fn=<DivBackward0>)


In [0]:
# Compute gradients (bacward pass through model)
loss.backward()

In [238]:
# Gradients for the weights
print("weights: ", w)
print("gradients for weights: ", w.grad)

# Gradients for the bias
print("bias: ", b)
print("gradients for bias: ", b.grad)

weights:  tensor([[0.3639, 1.7560]], requires_grad=True)
gradients for weights:  tensor([[-0.4951, -0.2991]])
bias:  tensor([-1.2370], requires_grad=True)
gradients for bias:  tensor([-1.3542])


In [239]:
# train for multiple epochs:
epochs = 100
lr = 1e-5

for i in range(epochs):
  preds = model(data)
  loss = mse(preds, target)
  print("epoch: ", i, "loss: ", loss)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * lr
    b -= b.grad * lr
    w.grad.zero_()
    b.grad.zero_()

epoch:  0 loss:  tensor(0.6344, grad_fn=<DivBackward0>)
epoch:  1 loss:  tensor(0.6344, grad_fn=<DivBackward0>)
epoch:  2 loss:  tensor(0.6344, grad_fn=<DivBackward0>)
epoch:  3 loss:  tensor(0.6343, grad_fn=<DivBackward0>)
epoch:  4 loss:  tensor(0.6343, grad_fn=<DivBackward0>)
epoch:  5 loss:  tensor(0.6343, grad_fn=<DivBackward0>)
epoch:  6 loss:  tensor(0.6343, grad_fn=<DivBackward0>)
epoch:  7 loss:  tensor(0.6343, grad_fn=<DivBackward0>)
epoch:  8 loss:  tensor(0.6342, grad_fn=<DivBackward0>)
epoch:  9 loss:  tensor(0.6342, grad_fn=<DivBackward0>)
epoch:  10 loss:  tensor(0.6342, grad_fn=<DivBackward0>)
epoch:  11 loss:  tensor(0.6342, grad_fn=<DivBackward0>)
epoch:  12 loss:  tensor(0.6342, grad_fn=<DivBackward0>)
epoch:  13 loss:  tensor(0.6341, grad_fn=<DivBackward0>)
epoch:  14 loss:  tensor(0.6341, grad_fn=<DivBackward0>)
epoch:  15 loss:  tensor(0.6341, grad_fn=<DivBackward0>)
epoch:  16 loss:  tensor(0.6341, grad_fn=<DivBackward0>)
epoch:  17 loss:  tensor(0.6340, grad_fn=

Second step: figure out how to do the linear model on the virtual workers. 

In [240]:
# Create a bob worker and an alice worker.
hook = sy.TorchHook(torch)
vw = sy.VirtualWorker(hook, id="vw")

print("vw worker: ", vw._objects)

W0716 06:03:47.788026 140222424659840 hook.py:98] Torch was already hooked... skipping hooking process


vw worker:  {94232955801: tensor([[1., 1.],
        [0., 1.],
        [1., 0.],
        [0., 0.]], requires_grad=True), 75922181708: tensor([[1.],
        [1.],
        [0.],
        [0.]], requires_grad=True), 44688912794: tensor([[0.2784, 2.5601]], requires_grad=True), 38860858928: tensor([-0.4879], requires_grad=True), 82961638445: tensor([[ 1.3505],
        [ 1.0722],
        [-0.2095],
        [-0.4879]], grad_fn=<SubBackward0>)}


In [0]:
# A Toy Dataset
# reinitialize and send to worker
data_ptr = torch.tensor([[1.,1],[0,1],[1,0],[0,0]], requires_grad=True).send(vw)
target_ptr = torch.tensor([[1.],[1], [0], [0]], requires_grad=True).send(vw)

In [0]:
# Generate weights and biases and send to worker
w_ptr= torch.randn(1, 2, requires_grad=True).send(vw)
b_ptr = torch.randn(1, requires_grad=True).send(vw)

In [243]:
# print vw
print(vw._objects)

{82961638445: tensor([[ 1.3505],
        [ 1.0722],
        [-0.2095],
        [-0.4879]], grad_fn=<SubBackward0>), 58200545665: tensor([[1., 1.],
        [0., 1.],
        [1., 0.],
        [0., 0.]], requires_grad=True), 57202235562: tensor([[1.],
        [1.],
        [0.],
        [0.]], requires_grad=True), 52380553883: tensor([[-0.7915,  0.1694]], requires_grad=True), 64468461730: tensor([-0.3217], requires_grad=True)}


In [244]:
# train the model virtually:
epochs = 100
lr = 1e-5

for i in range(epochs):
  # calculate predictions
  preds = data_ptr @ w_ptr.t() + b_ptr
  # calculate loss
  diff = preds - target_ptr
  loss = torch.sum(diff * diff) / diff.numel()
  # print output
  print("epoch: ", i, "loss: ", loss)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * lr
    b -= b.grad * lr
    w.grad.zero_()
    b.grad.zero_()

epoch:  0 loss:  (Wrapper)>[PointerTensor | me:7852246280 -> vw:55917896619]
epoch:  1 loss:  (Wrapper)>[PointerTensor | me:17643659430 -> vw:51810513046]
epoch:  2 loss:  (Wrapper)>[PointerTensor | me:51542092660 -> vw:86756348920]
epoch:  3 loss:  (Wrapper)>[PointerTensor | me:65962605451 -> vw:2848114858]
epoch:  4 loss:  (Wrapper)>[PointerTensor | me:52651841838 -> vw:41879360915]
epoch:  5 loss:  (Wrapper)>[PointerTensor | me:86255568012 -> vw:96892664970]
epoch:  6 loss:  (Wrapper)>[PointerTensor | me:70479287687 -> vw:55523604245]
epoch:  7 loss:  (Wrapper)>[PointerTensor | me:13439617704 -> vw:63103749277]
epoch:  8 loss:  (Wrapper)>[PointerTensor | me:79989768906 -> vw:59149038246]
epoch:  9 loss:  (Wrapper)>[PointerTensor | me:53500657362 -> vw:63783540064]
epoch:  10 loss:  (Wrapper)>[PointerTensor | me:1313960585 -> vw:23557126797]
epoch:  11 loss:  (Wrapper)>[PointerTensor | me:19250746191 -> vw:7621087706]
epoch:  12 loss:  (Wrapper)>[PointerTensor | me:48807586080 -> vw:

In [245]:
loss = loss.get()
print("loss: ", loss)

loss:  tensor(1.6122, requires_grad=True)


Instructor's work

In [246]:
input = torch.tensor([[1.,1], [0,1], [1,0], [0,0]], requires_grad=True).send(bob)
target = torch.tensor([[1.], [1], [0], [0]], requires_grad=True).send(bob)
print(input)
print(target)

(Wrapper)>[PointerTensor | me:1622412072 -> bob:28001469492]
(Wrapper)>[PointerTensor | me:86768162251 -> bob:96526002484]


In [247]:
weights = torch.tensor([[1.], [1]], requires_grad=True).send(bob)
print(weights)

(Wrapper)>[PointerTensor | me:54942580749 -> bob:75443871242]


In [248]:
pred = input.mm(weights)
print(pred)

(Wrapper)>[PointerTensor | me:66582509744 -> bob:91053147796]


In [0]:
loss = ((pred - target)**2).sum()

In [250]:
loss.backward()

(Wrapper)>[PointerTensor | me:60724472316 -> bob:99601149825]

In [251]:
weights.data.sub_(weights.grad * 0.1)
weights.grad *= 0

print(loss.get().data)

tensor(2.)


In [252]:
for i in range(10):
  pred = input.mm(weights)
  loss = ((pred - target)**2).sum()
  loss.backward()
  weights.data.sub_(weights.grad * 0.1)
  weights.grad *= 0

  print(loss.get().data)

tensor(0.5600)
tensor(0.2432)
tensor(0.1372)
tensor(0.0849)
tensor(0.0538)
tensor(0.0344)
tensor(0.0220)
tensor(0.0141)
tensor(0.0090)
tensor(0.0058)


# Lesson: Garbage Collection and Common Errors


In [0]:
bob = bob.clear_objects()

In [254]:
bob._objects

{}

In [0]:
x = torch.tensor([1,2,3,4,5]).send(bob)

In [256]:
bob._objects

{90068992324: tensor([1, 2, 3, 4, 5])}

In [0]:
del x

In [258]:
bob._objects

{}

In [0]:
x = torch.tensor([1,2,3,4,5]).send(bob)

In [260]:
bob._objects

{15058826800: tensor([1, 2, 3, 4, 5])}

In [0]:
x = "asdf"

In [262]:
bob._objects

{}

In [0]:
x = torch.tensor([1,2,3,4,5]).send(bob)

In [264]:
x

(Wrapper)>[PointerTensor | me:50210521639 -> bob:30494273952]

In [265]:
bob._objects

{30494273952: tensor([1, 2, 3, 4, 5])}

In [0]:
x = "asdf"

In [267]:
bob._objects

{30494273952: tensor([1, 2, 3, 4, 5])}

In [0]:
del x

In [269]:
bob._objects

{30494273952: tensor([1, 2, 3, 4, 5])}

In [270]:
bob = bob.clear_objects()
bob._objects

{}

In [0]:
for i in range(1000):
    x = torch.tensor([1,2,3,4,5]).send(bob)

In [272]:
bob._objects

{2051403999: tensor([1, 2, 3, 4, 5])}

In [0]:
x = torch.tensor([1,2,3,4,5]).send(bob)
y = torch.tensor([1,1,1,1,1])

In [274]:
z = x + y

TensorsNotCollocatedException: ignored

In [0]:
x = torch.tensor([1,2,3,4,5]).send(bob)
y = torch.tensor([1,1,1,1,1]).send(alice)

In [276]:
z = x + y

TensorsNotCollocatedException: ignored

# Lesson: Toy Federated Learning

Let's start by training a toy model the centralized way. This is about a simple as models get. We first need:

- a toy dataset
- a model
- some basic training logic for training a model to fit the data.

In [0]:
from torch import nn, optim

In [0]:
# A Toy Dataset
data = torch.tensor([[1.,1],[0,1],[1,0],[0,0]], requires_grad=True)
target = torch.tensor([[1.],[1], [0], [0]], requires_grad=True)

In [0]:
# A Toy Model
model = nn.Linear(2,1)

In [0]:
opt = optim.SGD(params=model.parameters(), lr=0.1)

In [281]:
def train(iterations=20):
    for iter in range(iterations):
        opt.zero_grad()

        pred = model(data)

        loss = ((pred - target)**2).sum()

        loss.backward()

        opt.step()

        print(loss.data)
        
train()

tensor(0.3304)
tensor(0.1514)
tensor(0.0929)
tensor(0.0595)
tensor(0.0384)
tensor(0.0248)
tensor(0.0161)
tensor(0.0104)
tensor(0.0068)
tensor(0.0044)
tensor(0.0029)
tensor(0.0019)
tensor(0.0013)
tensor(0.0008)
tensor(0.0006)
tensor(0.0004)
tensor(0.0002)
tensor(0.0002)
tensor(0.0001)
tensor(7.9857e-05)


In [0]:
data_bob = data[0:2].send(bob)
target_bob = target[0:2].send(bob)

In [0]:
data_alice = data[2:4].send(alice)
target_alice = target[2:4].send(alice)

In [0]:
datasets = [(data_bob, target_bob), (data_alice, target_alice)]

In [0]:
def train(iterations=20):

    model = nn.Linear(2,1)
    opt = optim.SGD(params=model.parameters(), lr=0.1)
    
    for iter in range(iterations):

        for _data, _target in datasets:

            # send model to the data
            model = model.send(_data.location)

            # do normal training
            opt.zero_grad()
            pred = model(_data)
            loss = ((pred - _target)**2).sum()
            loss.backward()
            opt.step()

            # get smarter model back
            model = model.get()

            print(loss.get())

In [286]:
train()

tensor(0.1186, requires_grad=True)
tensor(1.7156, requires_grad=True)
tensor(0.5091, requires_grad=True)
tensor(0.9260, requires_grad=True)
tensor(0.3385, requires_grad=True)
tensor(0.5501, requires_grad=True)
tensor(0.2000, requires_grad=True)
tensor(0.3307, requires_grad=True)
tensor(0.1178, requires_grad=True)
tensor(0.2002, requires_grad=True)
tensor(0.0698, requires_grad=True)
tensor(0.1220, requires_grad=True)
tensor(0.0417, requires_grad=True)
tensor(0.0750, requires_grad=True)
tensor(0.0252, requires_grad=True)
tensor(0.0465, requires_grad=True)
tensor(0.0154, requires_grad=True)
tensor(0.0292, requires_grad=True)
tensor(0.0095, requires_grad=True)
tensor(0.0185, requires_grad=True)
tensor(0.0060, requires_grad=True)
tensor(0.0118, requires_grad=True)
tensor(0.0039, requires_grad=True)
tensor(0.0077, requires_grad=True)
tensor(0.0025, requires_grad=True)
tensor(0.0050, requires_grad=True)
tensor(0.0017, requires_grad=True)
tensor(0.0034, requires_grad=True)
tensor(0.0011, requi

# Lesson: Advanced Remote Execution Tools

In the last section we trained a toy model using Federated Learning. We did this by calling .send() and .get() on our model, sending it to the location of training data, updating it, and then bringing it back. However, at the end of the example we realized that we needed to go a bit further to protect people privacy. Namely, we want to average the gradients BEFORE calling .get(). That way, we won't ever see anyone's exact gradient (thus better protecting their privacy!!!)

But, in order to do this, we need a few more pieces:

- use a pointer to send a Tensor directly to another worker

And in addition, while we're here, we're going to learn about a few more advanced tensor operations as well which will help us both with this example and a few in the future!

In [287]:
bob.clear_objects()
alice.clear_objects()

<VirtualWorker id:alice #objects:0>

In [0]:
x = torch.tensor([1,2,3,4,5]).send(bob)

In [0]:
x = x.send(alice)

In [290]:
bob._objects

{23806497411: tensor([1, 2, 3, 4, 5])}

In [291]:
alice._objects

{90549823888: (Wrapper)>[PointerTensor | alice:90549823888 -> bob:23806497411]}

In [0]:
y = x + x

In [293]:
y

(Wrapper)>[PointerTensor | me:87291445897 -> alice:21319100885]

In [294]:
bob._objects

{23806497411: tensor([1, 2, 3, 4, 5]),
 64952605752: tensor([ 2,  4,  6,  8, 10])}

In [295]:
alice._objects

{21319100885: (Wrapper)>[PointerTensor | alice:21319100885 -> bob:64952605752],
 90549823888: (Wrapper)>[PointerTensor | alice:90549823888 -> bob:23806497411]}

In [0]:
jon = sy.VirtualWorker(hook, id="jon")

In [0]:
bob.clear_objects()
alice.clear_objects()

x = torch.tensor([1,2,3,4,5]).send(bob).send(alice)

In [298]:
bob._objects

{80743909860: tensor([1, 2, 3, 4, 5])}

In [299]:
alice._objects

{25468552553: (Wrapper)>[PointerTensor | alice:25468552553 -> bob:80743909860]}

In [300]:
x = x.get()
x

(Wrapper)>[PointerTensor | me:25468552553 -> bob:80743909860]

In [301]:
bob._objects

{80743909860: tensor([1, 2, 3, 4, 5])}

In [302]:
alice._objects

{}

In [303]:
x = x.get()
x

tensor([1, 2, 3, 4, 5])

In [304]:
bob._objects

{}

In [0]:
bob.clear_objects()
alice.clear_objects()

x = torch.tensor([1,2,3,4,5]).send(bob).send(alice)

In [306]:
bob._objects

{11443659283: tensor([1, 2, 3, 4, 5])}

In [307]:
alice._objects

{24322346864: (Wrapper)>[PointerTensor | alice:24322346864 -> bob:11443659283]}

In [0]:
del x

In [309]:
bob._objects

{}

In [310]:
alice._objects

{}

# Lesson: Pointer Chain Operations

In [311]:
bob.clear_objects()
alice.clear_objects()

<VirtualWorker id:alice #objects:0>

In [0]:
x = torch.tensor([1,2,3,4,5]).send(bob)

In [313]:
bob._objects

{52876358928: tensor([1, 2, 3, 4, 5])}

In [314]:
alice._objects

{}

In [315]:
x.move(alice)

(Wrapper)>[PointerTensor | me:47809884307 -> alice:47809884307]

In [316]:
bob._objects

{}

In [317]:
alice._objects

{47809884307: tensor([1, 2, 3, 4, 5])}

In [0]:
x = torch.tensor([1,2,3,4,5]).send(bob).send(alice)

In [319]:
bob._objects

{72413873701: tensor([1, 2, 3, 4, 5])}

In [320]:
alice._objects

{33326531281: (Wrapper)>[PointerTensor | alice:33326531281 -> bob:72413873701],
 47809884307: tensor([1, 2, 3, 4, 5])}

In [321]:
x.remote_get()

(Wrapper)>[PointerTensor | me:14600201565 -> alice:33326531281]

In [322]:
bob._objects

{}

In [323]:
alice._objects

{33326531281: tensor([1, 2, 3, 4, 5]), 47809884307: tensor([1, 2, 3, 4, 5])}

In [324]:
x.move(bob)

(Wrapper)>[PointerTensor | me:14600201565 -> bob:14600201565]

In [325]:
x

(Wrapper)>[PointerTensor | me:14600201565 -> bob:14600201565]

In [326]:
bob._objects

{14600201565: tensor([1, 2, 3, 4, 5])}

In [327]:
alice._objects

{47809884307: tensor([1, 2, 3, 4, 5])}